# Generated by Django 5.2.3 on 2025-06-19 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('phone', models.CharField(max_length=16)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
